apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: fs-076d50beed2d680ef
  resources:
    requests:
      storage: 5Gi
      