kind: Pod
apiVersion: v1
metadata:
 name: resources
spec:
 containers:
  - name: nginx
    image: nginx
    resources:
     requests:
      memory: "68mi"
      cpu: "100"
     limits:
      memory: "128mi"
      cpu: "150m"
